# syntax=docker/dockerfile:1

# Download Go Dependencies
FROM golang:{{.GoVersion}}-alpine3.19 as base
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

# Build Go Binary
FROM golang:{{.GoVersion}}-alpine3.19 as builder
COPY --from=base /go/bin /go/bin
COPY --from=base /go/pkg /go/pkg
WORKDIR /app
COPY . ./
EXPOSE 8888
RUN CGO_ENABLED=0 GOOS=linux go build -o /{{.ProjectName}}

# Create Final Image
FROM gcr.io/distroless/base-debian11 as final
COPY --from=builder /{{.ProjectName}} /{{.ProjectName}}
ENTRYPOINT ["/{{.ProjectName}}"]
